spring:
  config:
    activate:
      on-profile: prod
  datasource:
   
    url: jdbc:postgresql://${DB_HOST:postgres-db}:5432/order_db
    username: ${DB_USER:akaslan_prod}
    password: ${DB_PASSWORD:SecureDbPass456!}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false 
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq-server}
    port: 5672
    username: ${RABBITMQ_USER:rabbit_admin}
    password: ${RABBITMQ_PASSWORD:SecureRabbitPass789!}
  security:
    oauth2:
      resourceserver:
        jwt:
         
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://34.122.181.181:9090/realms/akaslan}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

    hostname: order-service
