services:


  postgres:
    image: postgres:15-alpine
    container_name: akaslan-postgres
    environment:
      POSTGRES_USER: akaslan
      POSTGRES_PASSWORD: akaslan123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - akaslan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akaslan"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: akaslan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - akaslan-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: akaslan-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - akaslan-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: akaslan-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    networks:
      - akaslan-network

networks:
  akaslan-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
