server:
  port: 8083

spring:
  application:
    name: cart-service
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/akaslan/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

integration:
  cart:
    internal-api-key: ${INTERNAL_API_KEY:local-dev-internal-key}
